### ISSUE TITLE
Custom authenticators (e.g. aws-iam-authenticator)

### ISSUE THREAD

**Issue by ekevoo** [storax/kubedoom#8]
Here's an exerpt of my `~/.kube/config`

```
users:
- name: user1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - cluster-name.example.com
      - --forward-session-name
      command: aws-iam-authenticator
      env: null
```

This will call a system command (in my case it's in `/usr/local/bin/aws-iam-authenticator`) to use my existing AWS credentials to authenticate me into kubernetes.

What is the recommended way to provide this authenticator into kubedoom?
